sonar.projectKey=ucv-alpha-beta-lab
sonar.organization=tu-organizacion
sonar.projectName=UCV Alpha Beta Lab
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
